n_joints: 2
n_epochs: 3001
val_interval: 5
dataset:
  type: SupervisedTargetGaussianDataset  # Name of dataset type 
  mode: "IK_random_start" # "IK_const_start" "IK_random_start" "IK_random_start_constrained" "noise_uniform" "noise_tanh"  const is a dataset created with a constant start position -> one action for one target position, with random -> multiple actions for one target positions are possible
  batch_size: 2096
  shuffle: False
  action_constrain_radius: 0.2  # only available if dataset == conditional_action_target and conditional_target(here it will be used as std around the current position)
  std: 0.2
  target_mode: "ACTION"  # either POSITION or ACTION. POSITION is only applicable with distance loss while ACTION also enables imitation but needs to compute actions form ccd before hand  
  truncation: 0  # for truncated gaussian in TargetGaussianDataset
loss_func: 
  type: "IKLoss"  # ImitationLoss DistanceLoss MergeLoss PointDistanceLoss
  imitation_loss_weight: 0.01
  distance_loss_weight: 1
post_processor:
  enabled: True
  min_action: -1 # -3.142  # little offset to make it easier for tanh function
  max_action: 1 # 3.142  # little offset to make it easier for tanh function
model:
  architecture: [256, 256]
  activation_function: ReLU
  learning_rate: 0.0015
